### ISSUE TITLE
TypeError while instantiating model using torch.hub.load

### ISSUE THREAD

**Issue by quantumcoder121** [lpiccinelli-eth/UniDepth#18]
The error is as follows:

File "/home/interns/.cache/torch/hub/lpiccinelli-eth_UniDepth_main/unidepth/utils/visualization.py", line 39, in <module>
    def image_grid(imgs: list[np.ndarray], rows: int, cols: int) -> np.ndarray:
TypeError: 'type' object is not subscriptable

**Comment by lpiccinelli-eth** [comment]
It is due to having an older python version, i.e. <3.9, and did not support typing with built-in classes (e.g. `list` instead of `List` from typing module).

If you do not want to upgrade python, I think you can solve with:  `from __future__ import annotations`.

**Comment by quantumcoder121** [comment]
Ic thx a lot
well I just forked the repo and removed all the types in function declarations and it works well now
closing the issue

**Comment by quantumcoder121** [comment]
now closing the issue
