### ISSUE TITLE
Triton is not available

### ISSUE THREAD

**Issue by eldar** [lpiccinelli-eth/UniDepth#19]
Dear all,

Congrats on your excellent paper and thanks for putting the code out! I followed the instructions to set up the environment and while it works (I get the declared accuracy on the provided example), I do get a warning related to triton each time I import a UniDepth model class:

```
Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
```

Is this something I should be concerned about during training (finetuning) of your model or I can just ignore it?

**Comment by lpiccinelli-eth** [comment]
Thank you for your appreciation! 

That warning will lead to (considerably?) slower training and inference. 
This is due to having GPUs that are not supported by the installed Triton version.

**Comment by eldar** [comment]
You are right! I just tried on a more modern GPU (NVIDIA A40) and I do not get this error anymore. That must have been an old one. Thank you.
