### ISSUE TITLE
execute  predictions = model.infer(rgb),kernel restarting

### ISSUE THREAD

**Issue by wrx1990** [lpiccinelli-eth/UniDepth#21]
When I run the demo code, when 
`predictions = model.infer(rgb)`
 is executed, my notebook will suddenly disconnect.
<img width="854" alt="image" src="https://github.com/lpiccinelli-eth/UniDepth/assets/104119730/ca0464f5-9cd3-45eb-b46f-08fe1d0a4064">
 how to solved it!

**Comment by lpiccinelli-eth** [comment]
I think that there are two possible reasons, if you are on a GPU, it is going OOM, the model should use ~6GB of memory for inference. While if you are on CPU, the model is not meant to work on CPU and it will crash (due to triton usage).

**Comment by wrx1990** [comment]
> I think that there are two possible reasons, if you are on a GPU, it is going OOM, the model should use ~6GB of memory for inference. While if you are on CPU, the model is not meant to work on CPU and it will crash (due to triton usage).

The problem is that my cuda version is lower than the required version。
