### ISSUE TITLE
Youtube Video demo

### ISSUE THREAD

**Issue by ljjTYJR** [lpiccinelli-eth/UniDepth#27]
Thanks for the nice work!

I wonder how to reproduce the nice demo on the Github page with YouTube videos (**YouTube (The Office - Parkour)**)
Just inputting the consecutive video frames?

**Comment by lpiccinelli-eth** [comment]
Thank you! Yes, we downloaded the .mp4 and obtained the .png frames from it, then ran our model as in this repo, but we did not resize the output back to the original shape (HD), we kept it as our model output to avoid the heavy interpolation and save the pointcloud .ply as in #11. After, we used open3d visualizer and moved the camera a bit (to show the 3d structure) and save the visualization as a stream of frames and merge them to obtain the video.

**Comment by ljjTYJR** [comment]
Thanks! The scale estimation of the same scene looks consistent.
Nice work!
