### ISSUE TITLE
export to onnx

### ISSUE THREAD

**Issue by miiddb** [lpiccinelli-eth/UniDepth#34]
Hello,
Would it be possible to export the model into the .onnx format ?

**Comment by lpiccinelli-eth** [comment]
It is in our roadmap, we will release version2 an then the onnx exporter for it.

**Comment by lpiccinelli-eth** [comment]
It has been included in PR #38 which will release UniDepthV2 and  .`onnx` exporting for V2. 

You can check on the `version2` branch the `unidepth/models/unidepthv2/export.py` file and documentation under `assets/docs/V2_README.md` to export our model to `.onnx` format. You can give it a try if you want and give us any feedback, thanks!

**Comment by miiddb** [comment]
thanks, it seems to work!

**Comment by charleshuang880730** [comment]
> thanks, it seems to work! Now i'm waiting for the smaller versions!

@miiddb Hi, I would like to ask if you could provide the converted ONNX model. I encountered errors during the conversion process and urgently need the ONNX model for testing. I would greatly appreciate your help. Thank you.
