### ISSUE TITLE
Release of v2

### ISSUE THREAD

**Issue by szymanowiczs** [lpiccinelli-eth/UniDepth#36]
Hi @lpiccinelli-eth thanks for your fantastic work! Do you have an expected timeline on releasing v2?

**Comment by lpiccinelli-eth** [comment]
You can check the `version2` branch, we are currently testing it and the compatibility with V1, too. We are trying to integrate it all by tomorrow.

**Comment by szymanowiczs** [comment]
Fantastic, thanks!
