### ISSUE TITLE
Inference Time data

### ISSUE THREAD

**Issue by a-kungwani** [lpiccinelli-eth/UniDepth#41]
Hi, Thank you all for your great work with MMDE.

I would like to know if you have some inference time or speed data available on any GPUs or some benchmarks related to that. 

Best Regards
Aman

**Comment by lpiccinelli-eth** [comment]
Thank you for your like and the question! We have not benchmarked the performances, but we notice a significant drop in inference time for older GPUs, I suspect it is related to TRiton not supporting them.

We will try to add a simple benchmark to our README.
