### ISSUE TITLE
Known intrinsics not working as I expected

### ISSUE THREAD

**Issue by dsvilarkovic** [lpiccinelli-eth/UniDepth#50]
Hello, 
Following your README.md it says that in case I have my own ground truth intrinsics, I should define them as:
```
intrinsics_path = "assets/demo/intrinsics.npy"

# Load the intrinsics if available
intrinsics = torch.from_numpy(np.load(intrinsics_path)) # 3 x 3

predictions = model.infer(rgb, intrinsics)
``` 

I tried this in a small demo.ipynb, but I notice that my gt_intrinsics is corrected afterwards:

![image](https://github.com/lpiccinelli-eth/UniDepth/assets/18049803/6770109b-007c-4d80-88ee-bdb947c8e223)

Is there any way I can depth map estimation without changing my gt-intrinsics?

**Comment by lpiccinelli-eth** [comment]
Thank you for raising this issue.

You can check issue #48 for a more detailed explanation, in short: the intrinsic returned by the model are the estimated ones, if you provide some GT intrinsics the model will use the GT, but it will return the predicted ones anyway.

**Comment by dsvilarkovic** [comment]
All right, thanks for repeating the answer! I will close this issue, and test your module in the upcoming week, hoping it helps for dense keypoint initialization for splatting!
