### ISSUE TITLE
Size mismatch when loading UniDepth V2

### ISSUE THREAD

**Issue by Davidyao99** [lpiccinelli-eth/UniDepth#54]
Great work! I am trying to use the newer unidepthv2 model but am receiving this error:
![image](https://github.com/lpiccinelli-eth/UniDepth/assets/52120948/cb616193-2b08-45af-8d6b-df34aae12a60)
Any idea what I am doing wrong? This error does not occur when running the demo script with Unidepth V1.

Additionally, what do you mean by "Version 1 and 2 present similar performance but output of version 2 may look more nervous because more diversity is linked to lower GT quality, thus introducing artifacts...". What does "nervous" artifacts mean here?

**Comment by lpiccinelli-eth** [comment]
You can checkout on the branch `update_v2`, after the merging, also main will solved.

V2 has better out of domain performance, but by nervous I mean that the output sometimes is less smooth on borders with some tiny artifacts, this may be due to the larger input size, too.

**Comment by Davidyao99** [comment]
I see, it works now. Thank you so much for your prompt response!

**Comment by C-hongfei** [comment]
> I see, it works now. Thank you so much for your prompt response!

Hi,

I've encountered the same issue as well. I tried to checkout on the branch `update_v2`, but the problem still persists. Could you please share how you managed to resolve your issue?

Thanks!

**Comment by CuiOrange** [comment]
I have a similar problem when loading loading UniDepth V2

<img width="2455" height="699" alt="Image" src="https://github.com/user-attachments/assets/5ef7ef1b-7379-4ce8-be88-ff62615e77f8" />
