### ISSUE TITLE
Question on Depth Module

### ISSUE THREAD

**Issue by Aurelien-VB** [lpiccinelli-eth/UniDepth#6]
Thank you for this work ! 
I have troubles understanding the Depth Module and especially why the Keys and Values are taken from the Camera Embedding $E_1$ and not from the initial Depth Features $D$ coming from the encoder. 
Doesn't this lead to the model losing the information of the encoder ?

**Comment by lpiccinelli-eth** [comment]
Thank you for asking the question.

If I understand correctly, I think that this possible misunderstanding comes from the fact that, actually, there is a residual (skip) connection in the cross-attention between DepthFeatures and CameraEmbeddings. This means that the depth features are only "corrected" with the camera embeddings, namely `D = D + CrossAttn(D, E)`.

**Comment by Aurelien-VB** [comment]
Thanks for the quick answer, it makes sense !
